"""add pole user

Revision ID: d8ef7d9a8dc8
Revises: a13428575081
Create Date: 2024-10-17 16:24:53.329220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ef7d9a8dc8'
down_revision: Union[str, None] = 'a13428575081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('user', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'user')
    # ### end Alembic commands ###
